done
mate-academy/react_decompose pull request #233
Opened 2020-10-16 15:04 UTC by aionova

[DEMO LINK](https://aionova.github.io/react_decompose/)

2020-10-16 18:03 UTC, zkhomer approved these changes
вроде все окей )

2020-10-19 07:10 UTC, aliceblunt8 requested changes

2020-10-19 07:10 UTC, aliceblunt8 commented on src/components/Header/Header.js
> +}
it's not a Header, it should be a Welcome component

2020-10-19 07:10 UTC, aliceblunt8 commented on src/components/Nav/Nav.js
> +}
this should be Header
and you can have another component Nav inside of it

2020-10-19 08:08 UTC, aliceblunt8 approved these changes

2023-09-27 08:33 UTC, closed without merging