Solution
mate-academy/react_decompose pull request #404
Opened 2021-05-17 10:12 UTC by igor-stasiv

[DEMO LINK](https://igor-stasiv.github.io/react_decompose/)

2021-05-17 10:21 UTC, Burunduk003 approved these changes
Good job! You may do "main tag" as a separate component as well, but I suppose your solution also fits the task.

2021-05-18 07:42 UTC, VinnieJ-2k20 requested changes
Nice solution.
Just one edit needed.

2021-05-18 07:42 UTC, VinnieJ-2k20 commented on src/components/Header/Header.jsx
> +      </nav>
Let's move `Navigation` to separate component.

2021-05-18 08:59 UTC, VinnieJ-2k20 approved these changes
Good job 👍

2024-12-15 15:29 UTC, closed without merging