Develop
mate-academy/react_decompose pull request #430
Opened 2021-05-17 15:02 UTC by taya294

[DEMO LINK](https://taya294.github.io/react_decompose/)

2021-05-17 15:06 UTC, progmari approved these changes
Good job!

2021-05-18 07:30 UTC, VinnieJ-2k20 requested changes
You are on the right way.
But, some changes still needed.

First, let's organise your `components` folder.
You should have separate folder for each component, where its `.js` and `.css` files are stored.
Second, let's move Navigation to separate component.
Also, rearrange some styles. Don't mix styles for different components in one file.

2021-05-18 07:30 UTC, VinnieJ-2k20 commented on src/components/Article.css
> +  }
Let's move these styles to `header` styles.

2021-05-18 07:30 UTC, VinnieJ-2k20 commented on src/components/Header.jsx
> +      </nav>
Let's make a separate `Navigation` component.

2021-05-18 11:56 UTC, VinnieJ-2k20 approved these changes
Good job 👍

2021-07-15 09:39 UTC, closed without merging