Solution?
mate-academy/react_decompose pull request #481
Opened 2021-07-14 12:18 UTC by Vivdyuk

[DEMO LINK](https://vivdyuk.github.io/react_decompose/)

2021-07-14 14:18 UTC, vitaliy-martynyuk approved these changes
агонь(вроді як), глянь ще до мого пру будь-ласка

2021-07-15 07:50 UTC, aionova requested changes

2021-07-15 07:50 UTC, aionova commented on src/components/css/Header.css
> +.header {
файлы css должны лежать в папке самого компонента. то есть путь должен быть такой: src/components/Header/Header.css. и там же должен лежать js файл. чтобы все файлы, относящиеся к 1 компоненту, лежали в одном месте

2021-07-15 08:07 UTC, Vivdyuk commented on src/components/css/Header.css
> +.header {
Я не до кінця зрозумів умову і подумав, що мають бути окремо дві папки, в одній - всі **jsx**, в іншій -  всі **css**

2021-07-15 13:54 UTC, aionova approved these changes

2021-07-15 13:54 UTC, aionova commented on src/components/App/App.jsx
> +import React from 'react';
для App не нужна отдельная папка

2023-03-01 14:01 UTC, closed without merging