solution
mate-academy/react_decompose pull request #790
Opened 2022-02-10 15:08 UTC by maksym-mishchanchuk

[DEMO LINK](https://maksym-mishchanchuk.github.io/react_decompose/)

2022-02-10 21:05 UTC, jursylian approved these changes
Good job!!

2022-02-11 10:00 UTC, Anna-Tkachenko requested changes

2022-02-11 10:00 UTC, Anna-Tkachenko commented on src/components/Header/Header.css
> +  opacity: 1;
This styles should be in css file for Navigation component

2022-02-11 10:11 UTC, Anna-Tkachenko approved these changes
Good job 👍

2023-08-20 20:21 UTC, closed without merging