Solution
mate-academy/react_decompose pull request #981
Opened 2022-06-30 14:10 UTC by olya-yevsieienko

[DEMO LINK](https://olya-yevsieienko.github.io/react_decompose/)

2022-06-30 15:19 UTC, illavodonis requested changes

2022-06-30 15:19 UTC, illavodonis commented on src/components/Article/Article.css
> +}
Тут краще медіа запит для header перенести в файл  src/components/Header/Header.css

2022-06-30 15:21 UTC, illavodonis commented on src/components/Article/Article.css
> +}
Гарна робота, але треба дещо трішки змінити :fire:

2022-06-30 15:22 UTC, illavodonis commented
Гарна робота, але треба трішки дещо змінти :+1:

2022-07-01 10:12 UTC, mykola-koval approved these changes

2023-01-12 13:01 UTC, closed without merging